/*
  Created by Matthew Valancy
  Copyright 2026 Valpatel Software LLC
  Licensed under AGPL-3.0 — see LICENSE for details.

  MovementController JS mirror — exact field-name parity with Python
  tritium_lib.sim_engine.core.movement.MovementController.

  Handles waypoint-following with speed modulation, turn smoothing,
  and approach braking. Units move along paths generated by the A*
  pathfinder rather than teleporting between points.

  The tick() logic matches the Python implementation exactly:
    1. Get current target waypoint
    2. Check arrival (0.5m threshold)
    3. Calculate desired heading via atan2(dy, dx)
    4. Turn toward target (limited by turn_rate * dt)
    5. Speed modulation: slow for sharp turns (angle > 45deg)
       and approach braking within 2m (floor at 10% max speed)
    6. Accelerate/decelerate toward desired speed
    7. Move forward, clamping step to remaining distance
*/

// =========================================================================
// Angle utility
// =========================================================================

/**
 * Shortest signed angle difference from a to b, in degrees.
 * @param {number} a - Source angle in degrees
 * @param {number} b - Target angle in degrees
 * @returns {number} Signed difference in [-180, 180]
 */
export function angleDiff(a, b) {
    let diff = (b - a) % 360;
    if (diff > 180) diff -= 360;
    if (diff < -180) diff += 360;
    return diff;
}

// =========================================================================
// MovementController factory
// =========================================================================

/**
 * Create a movement controller with exact field-name parity to Python
 * MovementController dataclass.
 *
 * @param {Object} [props={}] - Initial property overrides
 * @returns {Object} Controller object with tick(), setPath(), stop(), etc.
 */
export function createMovementController(props = {}) {
    const mc = {
        // Configuration
        max_speed: props.max_speed !== undefined ? props.max_speed : 2.0,
        turn_rate: props.turn_rate !== undefined ? props.turn_rate : 180.0,  // degrees/sec
        acceleration: props.acceleration !== undefined ? props.acceleration : 4.0,  // m/s^2
        deceleration: props.deceleration !== undefined ? props.deceleration : 6.0,  // m/s^2

        // Current state
        x: props.x !== undefined ? props.x : 0.0,
        y: props.y !== undefined ? props.y : 0.0,
        heading: props.heading !== undefined ? props.heading : 0.0,  // degrees, 0=east, 90=north
        speed: 0.0,

        // Path following (private, prefixed with _ like Python)
        _waypoints: [],
        _waypoint_index: 0,
        _patrol_loop: false,

        // Status
        arrived: true,

        /**
         * Set a new path to follow.
         * Waypoints are [{x, y}, ...] or [[x, y], ...].
         * @param {Array} waypoints
         * @param {boolean} [loop=false]
         */
        setPath(waypoints, loop = false) {
            // Normalize to [x, y] tuples for internal use
            this._waypoints = waypoints.map(wp => {
                if (Array.isArray(wp)) return wp;
                return [wp.x, wp.y];
            });
            this._waypoint_index = 0;
            this._patrol_loop = loop;
            this.arrived = this._waypoints.length === 0;
        },

        /**
         * Alias for setPath (matches task spec naming).
         * @param {Array} waypoints
         * @param {boolean} [loop=false]
         */
        setWaypoints(waypoints, loop = false) {
            this.setPath(waypoints, loop);
        },

        /**
         * Simple: move to a single point.
         * @param {number} x
         * @param {number} y
         */
        setDestination(x, y) {
            this.setPath([[x, y]]);
        },

        /**
         * Stop movement, clear path.
         */
        stop() {
            this._waypoints = [];
            this._waypoint_index = 0;
            this.arrived = true;
        },

        /**
         * Advance movement by dt seconds.
         *
         * Logic matches Python MovementController.tick() exactly:
         *   1. Look at current waypoint target
         *   2. Calculate desired heading
         *   3. Turn toward target (limited by turn_rate)
         *   4. Accelerate/decelerate based on distance and angle
         *   5. Move forward
         *   6. Check arrival at waypoint
         *
         * @param {number} dt - Delta time in seconds
         */
        tick(dt) {
            if (this.arrived || this._waypoints.length === 0) {
                // Decelerate to stop
                this.speed = Math.max(0.0, this.speed - this.deceleration * dt);
                return;
            }

            const target = this._waypoints[this._waypoint_index];
            const dx = target[0] - this.x;
            const dy = target[1] - this.y;
            const dist = Math.sqrt(dx * dx + dy * dy);

            // Arrived at waypoint? (0.5m threshold)
            if (dist < 0.5) {
                this._waypoint_index += 1;
                if (this._waypoint_index >= this._waypoints.length) {
                    if (this._patrol_loop) {
                        this._waypoint_index = 0;
                    } else {
                        this.arrived = true;
                        this.speed = 0.0;
                        return;
                    }
                }
                return;  // Process next waypoint on next tick
            }

            // Desired heading (math convention: 0=east, CCW positive)
            const desired_heading = Math.atan2(dy, dx) * (180.0 / Math.PI);

            // Turn toward target (limited by turn_rate)
            const heading_diff = angleDiff(this.heading, desired_heading);
            const max_turn = this.turn_rate * dt;
            if (Math.abs(heading_diff) <= max_turn) {
                this.heading = desired_heading;
            } else {
                this.heading += max_turn * (heading_diff > 0 ? 1 : -1);
            }
            this.heading = ((this.heading % 360) + 360) % 360;

            // Speed modulation
            // Slow down for sharp turns
            const turn_factor = 1.0 - Math.min(Math.abs(heading_diff) / 90.0, 0.8);
            // Slow down approaching waypoint (brake within 2m, floor at 10% max speed)
            const approach_factor = Math.max(Math.min(dist / 2.0, 1.0), 0.1);

            const desired_speed = this.max_speed * turn_factor * approach_factor;

            // Accelerate/decelerate toward desired speed
            if (this.speed < desired_speed) {
                this.speed = Math.min(this.speed + this.acceleration * dt, desired_speed);
            } else {
                this.speed = Math.max(this.speed - this.deceleration * dt, desired_speed);
            }

            // Move — clamp step to remaining distance to prevent overshoot
            const step = this.speed * dt;
            if (step >= dist) {
                // Would overshoot — snap to waypoint
                this.x = target[0];
                this.y = target[1];
            } else {
                const rad = this.heading * (Math.PI / 180.0);
                this.x += Math.cos(rad) * step;
                this.y += Math.sin(rad) * step;
            }
        },

        /**
         * Get the current waypoint target, or null.
         * @returns {Array|null} [x, y] or null
         */
        get currentWaypoint() {
            if (this._waypoints.length > 0 && this._waypoint_index < this._waypoints.length) {
                return this._waypoints[this._waypoint_index];
            }
            return null;
        },

        /**
         * Get the number of remaining waypoints.
         * @returns {number}
         */
        get remainingWaypoints() {
            if (this._waypoints.length === 0) return 0;
            return Math.max(0, this._waypoints.length - this._waypoint_index);
        },
    };

    return mc;
}

// =========================================================================
// Path smoothing (mirrors Python smooth_path)
// =========================================================================

/**
 * Remove collinear waypoints within tolerance.
 * Simplifies paths by removing points that are nearly on a straight
 * line between their neighbors (Douglas-Peucker-like).
 *
 * @param {Array} waypoints - Array of [x, y] or {x, y}
 * @param {number} [tolerance=0.5]
 * @returns {Array} Simplified array of [x, y]
 */
export function smoothPath(waypoints, tolerance = 0.5) {
    // Normalize to [x, y]
    const pts = waypoints.map(wp => Array.isArray(wp) ? wp : [wp.x, wp.y]);

    if (pts.length <= 2) return pts.slice();

    const result = [pts[0]];
    for (let i = 1; i < pts.length - 1; i++) {
        const p0 = result[result.length - 1];
        const p1 = pts[i];
        const p2 = pts[i + 1];
        // Cross product magnitude = distance from line
        const cross = Math.abs(
            (p2[0] - p0[0]) * (p1[1] - p0[1]) - (p1[0] - p0[0]) * (p2[1] - p0[1])
        );
        const segLen = Math.sqrt(
            (p2[0] - p0[0]) ** 2 + (p2[1] - p0[1]) ** 2
        );
        const dist = segLen > 0 ? cross / segLen : 0;
        if (dist > tolerance) {
            result.push(p1);
        }
    }
    result.push(pts[pts.length - 1]);
    return result;
}
