# Created by Matthew Valancy
# Copyright 2026 Valpatel Software LLC
# Licensed under AGPL-3.0 — see LICENSE for details.
"""AnomalyEngine — real-time behavioral anomaly detection for tracked targets.

Learns normal behavior patterns per zone and time-of-day, then flags
deviations in speed, dwell time, route, and entity count.  Integrates
with EventBus for real-time alert publishing and with FusionEngine for
enriched anomaly context.

Anomaly types:

  - **speed**:  Target moving significantly faster/slower than zone baseline.
  - **dwell**:  Target lingering far longer than normal for the zone.
  - **count**:  Unusual number of targets in a zone for this time-of-day.
  - **route**:  Target appeared in a zone it has never been seen in before
                (or very rarely), suggesting an unusual route.
  - **reappearance**: Target reappeared after a long absence with a
                      suspicious pattern (e.g., same device, new location).

Each alert carries a severity (low / medium / high / critical) and a
numeric score (0.0 = normal, 1.0 = extremely anomalous).

Usage::

    from tritium_lib.intelligence.anomaly_engine import AnomalyEngine
    from tritium_lib.events.bus import EventBus

    bus = EventBus()
    engine = AnomalyEngine(event_bus=bus)

    # Feed observations to build baselines
    engine.observe("zone_lobby", target_id="ble_aa:bb", speed=1.2, dwell_seconds=120)
    engine.observe("zone_lobby", target_id="ble_cc:dd", speed=0.8, dwell_seconds=90)

    # After enough observations, check for anomalies
    alerts = engine.check_target("zone_lobby", target_id="ble_ee:ff",
                                 speed=15.0, dwell_seconds=5)
    # alerts -> [AnomalyAlert(type="speed", severity="high", ...)]
"""
from __future__ import annotations

import logging
import math
import threading
import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Optional

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class AnomalyAlert:
    """A single anomaly alert generated by the engine."""

    alert_type: str = ""          # speed, dwell, count, route, reappearance
    zone_id: str = ""
    target_id: str = ""
    severity: str = "low"         # low, medium, high, critical
    score: float = 0.0            # 0.0-1.0 anomaly score
    observed_value: float = 0.0
    baseline_mean: float = 0.0
    baseline_std: float = 0.0
    deviation_sigma: float = 0.0
    detail: str = ""
    timestamp: float = field(default_factory=time.time)
    suppressed: bool = False      # True if a known-pattern exclusion matched

    def to_dict(self) -> dict[str, Any]:
        return {
            "alert_type": self.alert_type,
            "zone_id": self.zone_id,
            "target_id": self.target_id,
            "severity": self.severity,
            "score": round(self.score, 4),
            "observed_value": round(self.observed_value, 4),
            "baseline_mean": round(self.baseline_mean, 4),
            "baseline_std": round(self.baseline_std, 4),
            "deviation_sigma": round(self.deviation_sigma, 2),
            "detail": self.detail,
            "timestamp": self.timestamp,
            "suppressed": self.suppressed,
        }


@dataclass
class ZoneBaseline:
    """Learned behavioral baseline for a single zone.

    Tracks rolling statistics for speed, dwell time, and entity count
    segmented by hour-of-day (24 buckets).
    """

    zone_id: str = ""

    # Per-hour-of-day statistics: hour -> list of values
    speed_by_hour: dict[int, list[float]] = field(
        default_factory=lambda: defaultdict(list)
    )
    dwell_by_hour: dict[int, list[float]] = field(
        default_factory=lambda: defaultdict(list)
    )
    count_by_hour: dict[int, list[float]] = field(
        default_factory=lambda: defaultdict(list)
    )

    # Global (all-hours) observations for when hourly data is sparse
    speed_all: list[float] = field(default_factory=list)
    dwell_all: list[float] = field(default_factory=list)
    count_all: list[float] = field(default_factory=list)

    # Targets seen in this zone: target_id -> visit count
    target_visits: dict[str, int] = field(default_factory=lambda: defaultdict(int))

    # Total observations used for this baseline
    observation_count: int = 0

    # Maximum samples to retain per hour bucket (rolling window)
    max_samples_per_hour: int = 500

    # Maximum samples for global lists
    max_global_samples: int = 5000


@dataclass
class KnownPattern:
    """A known pattern to exclude from anomaly detection (false-positive suppression).

    If a target/zone combination matches a known pattern, the anomaly is
    generated but marked as ``suppressed=True`` so consumers can filter it.
    """

    pattern_id: str = ""
    zone_id: str = ""               # empty = any zone
    target_id: str = ""             # empty = any target
    alert_type: str = ""            # empty = any type
    max_value: float = float("inf") # suppress if observed <= max_value
    min_value: float = float("-inf") # suppress if observed >= min_value
    reason: str = ""


# ---------------------------------------------------------------------------
# Statistics helpers
# ---------------------------------------------------------------------------

def _mean_std(values: list[float]) -> tuple[float, float]:
    """Compute mean and population std of a list. Returns (0, 0) if empty."""
    if not values:
        return 0.0, 0.0
    n = len(values)
    mean = sum(values) / n
    variance = sum((v - mean) ** 2 for v in values) / n
    std = math.sqrt(variance) if variance > 0 else 0.0
    return mean, std


def _severity_from_sigma(sigma: float) -> str:
    """Map sigma deviation to a severity label."""
    if sigma >= 5.0:
        return "critical"
    if sigma >= 4.0:
        return "high"
    if sigma >= 3.0:
        return "medium"
    return "low"


def _score_from_sigma(sigma: float) -> float:
    """Map sigma deviation to a 0-1 score."""
    return min(1.0, sigma / 5.0)


# ---------------------------------------------------------------------------
# AnomalyEngine
# ---------------------------------------------------------------------------

class AnomalyEngine:
    """Real-time behavioral anomaly detection engine.

    Learns zone-level baselines from observations and detects deviations
    in speed, dwell time, entity count, and route patterns.

    Thread-safe — all public methods acquire the internal lock.

    Parameters
    ----------
    event_bus:
        Optional EventBus instance. When provided, anomaly alerts are
        published to ``anomaly.alert`` and ``anomaly.alert.{type}``.
    min_baseline_samples:
        Minimum observations before anomaly detection activates per zone.
    speed_threshold_sigma:
        Standard deviations for speed anomaly (default 2.5).
    dwell_threshold_sigma:
        Standard deviations for dwell anomaly (default 2.5).
    count_threshold_sigma:
        Standard deviations for count anomaly (default 2.5).
    route_min_visits:
        Minimum zone visits across all targets before a target with
        zero visits is flagged as a route anomaly.
    cooldown_seconds:
        Minimum time between alerts for the same target+zone+type.
    """

    def __init__(
        self,
        event_bus=None,
        *,
        min_baseline_samples: int = 10,
        speed_threshold_sigma: float = 2.5,
        dwell_threshold_sigma: float = 2.5,
        count_threshold_sigma: float = 2.5,
        route_min_visits: int = 20,
        cooldown_seconds: float = 60.0,
    ) -> None:
        self._event_bus = event_bus
        self._lock = threading.Lock()

        # Configuration
        self._min_samples = min_baseline_samples
        self._speed_sigma = speed_threshold_sigma
        self._dwell_sigma = dwell_threshold_sigma
        self._count_sigma = count_threshold_sigma
        self._route_min_visits = route_min_visits
        self._cooldown = cooldown_seconds

        # Zone baselines: zone_id -> ZoneBaseline
        self._baselines: dict[str, ZoneBaseline] = {}

        # Known patterns for false-positive suppression
        self._known_patterns: list[KnownPattern] = []

        # Alert cooldown tracker: (target_id, zone_id, alert_type) -> last alert time
        self._cooldowns: dict[tuple[str, str, str], float] = {}

        # Alert history (bounded)
        self._alert_history: list[AnomalyAlert] = []
        self._max_history = 10000

        # Counters
        self._total_observations = 0
        self._total_alerts = 0
        self._total_suppressed = 0

    # ------------------------------------------------------------------
    # Baseline learning
    # ------------------------------------------------------------------

    def observe(
        self,
        zone_id: str,
        *,
        target_id: str = "",
        speed: float | None = None,
        dwell_seconds: float | None = None,
        entity_count: float | None = None,
        hour_of_day: int | None = None,
        timestamp: float | None = None,
    ) -> None:
        """Record an observation to update zone baselines.

        Call this for every target update / zone snapshot to build the
        behavioral baseline. The engine needs at least ``min_baseline_samples``
        observations per zone before anomaly detection activates.

        Parameters
        ----------
        zone_id:
            Zone this observation belongs to.
        target_id:
            Target being observed (for route tracking).
        speed:
            Target speed in m/s (None to skip speed baseline).
        dwell_seconds:
            How long the target has been in this zone (None to skip).
        entity_count:
            Current number of entities in this zone (None to skip).
        hour_of_day:
            Hour (0-23). If None, derived from timestamp or current time.
        timestamp:
            Observation time (epoch). Defaults to now.
        """
        ts = timestamp or time.time()
        if hour_of_day is None:
            hour_of_day = time.localtime(ts).tm_hour

        with self._lock:
            bl = self._get_or_create_baseline(zone_id)
            bl.observation_count += 1
            self._total_observations += 1

            if speed is not None:
                bl.speed_by_hour[hour_of_day].append(speed)
                bl.speed_all.append(speed)
                self._trim_list(bl.speed_by_hour[hour_of_day], bl.max_samples_per_hour)
                self._trim_list(bl.speed_all, bl.max_global_samples)

            if dwell_seconds is not None:
                bl.dwell_by_hour[hour_of_day].append(dwell_seconds)
                bl.dwell_all.append(dwell_seconds)
                self._trim_list(bl.dwell_by_hour[hour_of_day], bl.max_samples_per_hour)
                self._trim_list(bl.dwell_all, bl.max_global_samples)

            if entity_count is not None:
                bl.count_by_hour[hour_of_day].append(entity_count)
                bl.count_all.append(entity_count)
                self._trim_list(bl.count_by_hour[hour_of_day], bl.max_samples_per_hour)
                self._trim_list(bl.count_all, bl.max_global_samples)

            if target_id:
                bl.target_visits[target_id] += 1

    def observe_batch(
        self,
        observations: list[dict[str, Any]],
    ) -> int:
        """Bulk-ingest observations. Each dict has keys matching ``observe()`` params.

        Returns the number of observations processed.
        """
        count = 0
        for obs in observations:
            zone_id = obs.get("zone_id", "")
            if not zone_id:
                continue
            self.observe(
                zone_id,
                target_id=obs.get("target_id", ""),
                speed=obs.get("speed"),
                dwell_seconds=obs.get("dwell_seconds"),
                entity_count=obs.get("entity_count"),
                hour_of_day=obs.get("hour_of_day"),
                timestamp=obs.get("timestamp"),
            )
            count += 1
        return count

    # ------------------------------------------------------------------
    # Anomaly detection
    # ------------------------------------------------------------------

    def check_target(
        self,
        zone_id: str,
        *,
        target_id: str = "",
        speed: float | None = None,
        dwell_seconds: float | None = None,
        hour_of_day: int | None = None,
        timestamp: float | None = None,
    ) -> list[AnomalyAlert]:
        """Check a single target observation against zone baselines.

        Returns a list of AnomalyAlert for any detected anomalies.
        Alerts are also published to the EventBus if configured.
        """
        ts = timestamp or time.time()
        if hour_of_day is None:
            hour_of_day = time.localtime(ts).tm_hour

        alerts: list[AnomalyAlert] = []

        with self._lock:
            bl = self._baselines.get(zone_id)
            if bl is None:
                return alerts

            # Speed anomaly
            if speed is not None:
                alert = self._check_metric(
                    bl, "speed", speed, hour_of_day,
                    bl.speed_by_hour, bl.speed_all,
                    self._speed_sigma, zone_id, target_id, ts,
                )
                if alert:
                    alerts.append(alert)

            # Dwell anomaly
            if dwell_seconds is not None:
                alert = self._check_metric(
                    bl, "dwell", dwell_seconds, hour_of_day,
                    bl.dwell_by_hour, bl.dwell_all,
                    self._dwell_sigma, zone_id, target_id, ts,
                )
                if alert:
                    alerts.append(alert)

            # Route anomaly (target never/rarely seen in this zone)
            if target_id:
                alert = self._check_route(bl, zone_id, target_id, ts)
                if alert:
                    alerts.append(alert)

        # Publish alerts (outside lock to avoid deadlock with bus subscribers)
        for alert in alerts:
            self._publish_alert(alert)

        return alerts

    def check_zone_count(
        self,
        zone_id: str,
        current_count: float,
        *,
        hour_of_day: int | None = None,
        timestamp: float | None = None,
    ) -> AnomalyAlert | None:
        """Check if the entity count in a zone is anomalous.

        This is separate from ``check_target`` because count is a
        zone-level metric, not per-target.

        Returns an AnomalyAlert or None.
        """
        ts = timestamp or time.time()
        if hour_of_day is None:
            hour_of_day = time.localtime(ts).tm_hour

        with self._lock:
            bl = self._baselines.get(zone_id)
            if bl is None:
                return None

            alert = self._check_metric(
                bl, "count", current_count, hour_of_day,
                bl.count_by_hour, bl.count_all,
                self._count_sigma, zone_id, "", ts,
            )

        if alert:
            self._publish_alert(alert)
        return alert

    def check_reappearance(
        self,
        zone_id: str,
        target_id: str,
        absence_seconds: float,
        *,
        timestamp: float | None = None,
    ) -> AnomalyAlert | None:
        """Check if a target reappearing after a long absence is anomalous.

        A target that was gone for a very long time and suddenly reappears
        may warrant investigation (e.g., device clone, stolen device reuse).

        Parameters
        ----------
        zone_id:
            Zone the target reappeared in.
        target_id:
            The target ID.
        absence_seconds:
            How long the target was absent before reappearing.
        """
        ts = timestamp or time.time()

        # A reappearance is anomalous if the absence exceeds a threshold.
        # We use 24 hours as a baseline "normal absence" and flag anything
        # significantly longer.
        normal_absence = 86400.0  # 24 hours
        if absence_seconds <= normal_absence:
            return None

        ratio = absence_seconds / normal_absence
        sigma = ratio  # 1 sigma per day of absence
        if sigma < 2.0:
            return None

        severity = _severity_from_sigma(sigma)
        score = _score_from_sigma(sigma)

        alert = AnomalyAlert(
            alert_type="reappearance",
            zone_id=zone_id,
            target_id=target_id,
            severity=severity,
            score=score,
            observed_value=absence_seconds,
            baseline_mean=normal_absence,
            baseline_std=normal_absence * 0.5,
            deviation_sigma=round(sigma, 2),
            detail=(
                f"Target {target_id} reappeared in {zone_id} after "
                f"{absence_seconds/3600:.1f}h absence (expected <24h)"
            ),
            timestamp=ts,
        )

        with self._lock:
            alert = self._apply_known_patterns(alert)

        if not alert.suppressed:
            self._publish_alert(alert)
        return alert

    # ------------------------------------------------------------------
    # Known pattern management (false-positive suppression)
    # ------------------------------------------------------------------

    def add_known_pattern(self, pattern: KnownPattern) -> None:
        """Register a known pattern for false-positive suppression."""
        with self._lock:
            self._known_patterns.append(pattern)

    def remove_known_pattern(self, pattern_id: str) -> bool:
        """Remove a known pattern by ID. Returns True if found and removed."""
        with self._lock:
            before = len(self._known_patterns)
            self._known_patterns = [
                p for p in self._known_patterns if p.pattern_id != pattern_id
            ]
            return len(self._known_patterns) < before

    def get_known_patterns(self) -> list[KnownPattern]:
        """Return a copy of all known patterns."""
        with self._lock:
            return list(self._known_patterns)

    # ------------------------------------------------------------------
    # Query methods
    # ------------------------------------------------------------------

    def get_baseline(self, zone_id: str) -> ZoneBaseline | None:
        """Return the learned baseline for a zone, or None."""
        with self._lock:
            bl = self._baselines.get(zone_id)
            if bl is None:
                return None
            # Return a shallow copy so the caller can inspect without holding the lock
            return ZoneBaseline(
                zone_id=bl.zone_id,
                speed_by_hour=dict(bl.speed_by_hour),
                dwell_by_hour=dict(bl.dwell_by_hour),
                count_by_hour=dict(bl.count_by_hour),
                speed_all=list(bl.speed_all),
                dwell_all=list(bl.dwell_all),
                count_all=list(bl.count_all),
                target_visits=dict(bl.target_visits),
                observation_count=bl.observation_count,
            )

    def get_zone_stats(self, zone_id: str, hour: int | None = None) -> dict[str, Any]:
        """Return computed statistics for a zone baseline.

        If ``hour`` is provided, returns hour-specific stats; otherwise
        returns global stats.
        """
        with self._lock:
            bl = self._baselines.get(zone_id)
            if bl is None:
                return {"zone_id": zone_id, "status": "no_baseline"}

            if hour is not None:
                speed_mean, speed_std = _mean_std(bl.speed_by_hour.get(hour, []))
                dwell_mean, dwell_std = _mean_std(bl.dwell_by_hour.get(hour, []))
                count_mean, count_std = _mean_std(bl.count_by_hour.get(hour, []))
                speed_n = len(bl.speed_by_hour.get(hour, []))
                dwell_n = len(bl.dwell_by_hour.get(hour, []))
                count_n = len(bl.count_by_hour.get(hour, []))
            else:
                speed_mean, speed_std = _mean_std(bl.speed_all)
                dwell_mean, dwell_std = _mean_std(bl.dwell_all)
                count_mean, count_std = _mean_std(bl.count_all)
                speed_n = len(bl.speed_all)
                dwell_n = len(bl.dwell_all)
                count_n = len(bl.count_all)

            return {
                "zone_id": zone_id,
                "hour": hour,
                "observation_count": bl.observation_count,
                "unique_targets": len(bl.target_visits),
                "speed": {
                    "mean": round(speed_mean, 4),
                    "std": round(speed_std, 4),
                    "samples": speed_n,
                },
                "dwell": {
                    "mean": round(dwell_mean, 4),
                    "std": round(dwell_std, 4),
                    "samples": dwell_n,
                },
                "count": {
                    "mean": round(count_mean, 4),
                    "std": round(count_std, 4),
                    "samples": count_n,
                },
            }

    def get_alert_history(
        self,
        limit: int = 100,
        zone_id: str = "",
        target_id: str = "",
        alert_type: str = "",
        include_suppressed: bool = False,
    ) -> list[AnomalyAlert]:
        """Retrieve recent alerts, optionally filtered."""
        with self._lock:
            alerts = list(self._alert_history)

        if not include_suppressed:
            alerts = [a for a in alerts if not a.suppressed]
        if zone_id:
            alerts = [a for a in alerts if a.zone_id == zone_id]
        if target_id:
            alerts = [a for a in alerts if a.target_id == target_id]
        if alert_type:
            alerts = [a for a in alerts if a.alert_type == alert_type]

        # Most recent first
        alerts.sort(key=lambda a: a.timestamp, reverse=True)
        return alerts[:limit]

    def get_stats(self) -> dict[str, Any]:
        """Engine-wide statistics."""
        with self._lock:
            zone_count = len(self._baselines)
            return {
                "total_observations": self._total_observations,
                "total_alerts": self._total_alerts,
                "total_suppressed": self._total_suppressed,
                "zone_count": zone_count,
                "known_patterns": len(self._known_patterns),
                "alert_history_size": len(self._alert_history),
                "cooldown_entries": len(self._cooldowns),
                "config": {
                    "min_baseline_samples": self._min_samples,
                    "speed_threshold_sigma": self._speed_sigma,
                    "dwell_threshold_sigma": self._dwell_sigma,
                    "count_threshold_sigma": self._count_sigma,
                    "route_min_visits": self._route_min_visits,
                    "cooldown_seconds": self._cooldown,
                },
            }

    def reset(self, zone_id: str | None = None) -> None:
        """Reset baselines. If zone_id is given, resets only that zone."""
        with self._lock:
            if zone_id:
                self._baselines.pop(zone_id, None)
            else:
                self._baselines.clear()
                self._cooldowns.clear()
                self._alert_history.clear()
                self._total_observations = 0
                self._total_alerts = 0
                self._total_suppressed = 0

    # ------------------------------------------------------------------
    # FusionEngine integration
    # ------------------------------------------------------------------

    def ingest_from_fusion(
        self,
        fused_targets: list[Any],
        zone_assignments: dict[str, set[str]] | None = None,
    ) -> list[AnomalyAlert]:
        """Ingest targets from FusionEngine and check for anomalies.

        Parameters
        ----------
        fused_targets:
            List of FusedTarget or TrackedTarget objects (duck-typed).
            Must have ``target_id``, ``speed``, ``position`` attributes.
        zone_assignments:
            Optional mapping of zone_id -> set of target_ids currently
            in that zone. If provided, also checks zone count anomalies.

        Returns
        -------
        list[AnomalyAlert]:
            All anomaly alerts generated.
        """
        all_alerts: list[AnomalyAlert] = []

        for target in fused_targets:
            tid = getattr(target, "target_id", "")
            spd = getattr(target, "speed", None)

            # Determine zone(s) for this target
            zones: set[str] = set()
            if hasattr(target, "zones") and target.zones:
                zones = set(target.zones)
            elif zone_assignments:
                for zid, tids in zone_assignments.items():
                    if tid in tids:
                        zones.add(zid)

            for zid in zones:
                # Observe to continue learning
                self.observe(zid, target_id=tid, speed=spd)
                # Check for anomalies
                alerts = self.check_target(zid, target_id=tid, speed=spd)
                all_alerts.extend(alerts)

        # Zone count anomalies
        if zone_assignments:
            for zid, tids in zone_assignments.items():
                count = len(tids)
                self.observe(zid, entity_count=float(count))
                alert = self.check_zone_count(zid, float(count))
                if alert:
                    all_alerts.append(alert)

        return all_alerts

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_or_create_baseline(self, zone_id: str) -> ZoneBaseline:
        """Get or create a ZoneBaseline. Caller must hold self._lock."""
        if zone_id not in self._baselines:
            self._baselines[zone_id] = ZoneBaseline(zone_id=zone_id)
        return self._baselines[zone_id]

    @staticmethod
    def _trim_list(lst: list, max_size: int) -> None:
        """Trim a list to max_size by removing oldest entries."""
        if len(lst) > max_size:
            del lst[: len(lst) - max_size]

    def _check_metric(
        self,
        bl: ZoneBaseline,
        alert_type: str,
        observed: float,
        hour: int,
        hourly_data: dict[int, list[float]],
        global_data: list[float],
        threshold_sigma: float,
        zone_id: str,
        target_id: str,
        ts: float,
    ) -> AnomalyAlert | None:
        """Check a single metric against its baseline. Caller holds lock."""
        # Prefer hourly data if sufficient, else fall back to global
        hourly_values = hourly_data.get(hour, [])
        if len(hourly_values) >= self._min_samples:
            values = hourly_values
        elif len(global_data) >= self._min_samples:
            values = global_data
        else:
            return None  # Not enough data

        mean, std = _mean_std(values)

        if std < 1e-9:
            # Near-zero variance: flag any notable deviation from mean
            if abs(observed - mean) < 0.5:
                return None
            deviation = 10.0
        else:
            deviation = abs(observed - mean) / std

        if deviation < threshold_sigma:
            return None

        # Check cooldown
        cooldown_key = (target_id, zone_id, alert_type)
        last_alert_ts = self._cooldowns.get(cooldown_key, 0.0)
        if (ts - last_alert_ts) < self._cooldown:
            return None

        severity = _severity_from_sigma(deviation)
        score = _score_from_sigma(deviation)

        direction = "above" if observed > mean else "below"
        detail = (
            f"{alert_type.capitalize()} anomaly in {zone_id}: "
            f"observed={observed:.2f} vs baseline {mean:.2f} +/- {std:.2f} "
            f"({deviation:.1f} sigma {direction})"
        )

        alert = AnomalyAlert(
            alert_type=alert_type,
            zone_id=zone_id,
            target_id=target_id,
            severity=severity,
            score=score,
            observed_value=observed,
            baseline_mean=mean,
            baseline_std=std,
            deviation_sigma=round(deviation, 2),
            detail=detail,
            timestamp=ts,
        )

        alert = self._apply_known_patterns(alert)

        # Update cooldown and history
        self._cooldowns[cooldown_key] = ts
        self._alert_history.append(alert)
        self._total_alerts += 1
        if alert.suppressed:
            self._total_suppressed += 1

        # Trim history
        if len(self._alert_history) > self._max_history:
            self._alert_history = self._alert_history[-self._max_history:]

        return alert

    def _check_route(
        self,
        bl: ZoneBaseline,
        zone_id: str,
        target_id: str,
        ts: float,
    ) -> AnomalyAlert | None:
        """Check if a target appearing in this zone is a route anomaly.

        A route anomaly means the target has never (or very rarely) been
        seen in this zone, while the zone itself has plenty of visits
        from other targets.

        Caller holds lock.
        """
        total_unique = len(bl.target_visits)
        if total_unique < self._route_min_visits:
            return None  # Not enough diversity to judge

        target_count = bl.target_visits.get(target_id, 0)
        if target_count > 0:
            return None  # Target has been here before, not a route anomaly

        # Check cooldown
        cooldown_key = (target_id, zone_id, "route")
        last_alert_ts = self._cooldowns.get(cooldown_key, 0.0)
        if (ts - last_alert_ts) < self._cooldown:
            return None

        # Compute how unusual it is: use total_unique as a proxy for
        # "how many distinct targets visit this zone"
        avg_visits = bl.observation_count / max(total_unique, 1)
        severity = "medium" if total_unique > 50 else "low"
        score = min(1.0, total_unique / 100.0)

        alert = AnomalyAlert(
            alert_type="route",
            zone_id=zone_id,
            target_id=target_id,
            severity=severity,
            score=score,
            observed_value=0.0,
            baseline_mean=avg_visits,
            baseline_std=0.0,
            deviation_sigma=0.0,
            detail=(
                f"Target {target_id} first seen in {zone_id} — "
                f"{total_unique} unique targets previously visited "
                f"(avg {avg_visits:.1f} visits each)"
            ),
            timestamp=ts,
        )

        alert = self._apply_known_patterns(alert)

        self._cooldowns[cooldown_key] = ts
        self._alert_history.append(alert)
        self._total_alerts += 1
        if alert.suppressed:
            self._total_suppressed += 1

        if len(self._alert_history) > self._max_history:
            self._alert_history = self._alert_history[-self._max_history:]

        return alert

    def _apply_known_patterns(self, alert: AnomalyAlert) -> AnomalyAlert:
        """Check if an alert matches any known pattern. Caller holds lock."""
        for pattern in self._known_patterns:
            if pattern.zone_id and pattern.zone_id != alert.zone_id:
                continue
            if pattern.target_id and pattern.target_id != alert.target_id:
                continue
            if pattern.alert_type and pattern.alert_type != alert.alert_type:
                continue
            if alert.observed_value > pattern.max_value:
                continue
            if alert.observed_value < pattern.min_value:
                continue
            # Pattern matches — suppress
            alert.suppressed = True
            alert.detail += f" [suppressed by pattern {pattern.pattern_id}: {pattern.reason}]"
            break
        return alert

    def _publish_alert(self, alert: AnomalyAlert) -> None:
        """Publish alert to EventBus if available."""
        if self._event_bus is None:
            return
        if alert.suppressed:
            return

        try:
            self._event_bus.publish(
                f"anomaly.alert.{alert.alert_type}",
                data=alert.to_dict(),
                source="anomaly_engine",
            )
            self._event_bus.publish(
                "anomaly.alert",
                data=alert.to_dict(),
                source="anomaly_engine",
            )
        except Exception:
            log.debug("Failed to publish anomaly alert to EventBus", exc_info=True)
